In [1]:
import numpy as np

# 1.创建一个5×5的随机矩阵，提取第2行（索引从0开始

In [24]:
np.random.seed(520)
arr=np.random.rand(5,5)
print(arr)
print("\n")
print(arr[1])  #1
print(arr[1,:])  #2

[[0.44191901 0.20766077 0.01457911 0.44353579 0.65532275]
 [0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]
 [0.98530729 0.75944085 0.45066569 0.05489313 0.04557808]
 [0.01707102 0.0283987  0.46486698 0.58650204 0.59542199]
 [0.21561468 0.43811321 0.02209366 0.49294138 0.27898905]]


[0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]
[0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]


# 2. 提取上述矩阵的第1列和第3列。

In [28]:
print(arr[:,0])
print(arr[:,2])

[0.44191901 0.3123031  0.98530729 0.01707102 0.21561468]
[0.01457911 0.37385244 0.45066569 0.46486698 0.02209366]


# 3. 提取矩阵的2-4行、1-3列（左闭右开）。

In [37]:
print(arr[1:4,:]) #连续取法
print(arr[:,0:3])
print(arr[[1,3],:]) #非连续取法
print(arr[:,[0,2]])

[[0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]
 [0.98530729 0.75944085 0.45066569 0.05489313 0.04557808]
 [0.01707102 0.0283987  0.46486698 0.58650204 0.59542199]]
[[0.44191901 0.20766077 0.01457911]
 [0.3123031  0.05961261 0.37385244]
 [0.98530729 0.75944085 0.45066569]
 [0.01707102 0.0283987  0.46486698]
 [0.21561468 0.43811321 0.02209366]]
[[0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]
 [0.01707102 0.0283987  0.46486698 0.58650204 0.59542199]]
[[0.44191901 0.01457911]
 [0.3123031  0.37385244]
 [0.98530729 0.45066569]
 [0.01707102 0.46486698]
 [0.21561468 0.02209366]]


# 4. 提取矩阵中所有偶数行、奇数列。

In [40]:
print("偶数")
print(arr[1::2,:])   #步长

偶数
[[0.3123031  0.05961261 0.37385244 0.20484334 0.20830399]
 [0.01707102 0.0283987  0.46486698 0.58650204 0.59542199]]


# 5. 将矩阵的中心3×3子矩阵全部赋值为0。

In [44]:
arr[1:4,1:4]=0
print(arr)

[[0.44191901 0.20766077 0.01457911 0.44353579 0.65532275]
 [0.3123031  0.         0.         0.         0.20830399]
 [0.98530729 0.         0.         0.         0.04557808]
 [0.01707102 0.         0.         0.         0.59542199]
 [0.21561468 0.43811321 0.02209366 0.49294138 0.27898905]]


# 6. 使用花式索引提取指定行[0,2,4]。

In [45]:
print(arr[[0,2,4],:])

[[0.44191901 0.20766077 0.01457911 0.44353579 0.65532275]
 [0.98530729 0.         0.         0.         0.04557808]
 [0.21561468 0.43811321 0.02209366 0.49294138 0.27898905]]


# 7. 使用花式索引提取指定列[1,3]并组成新矩阵。

In [46]:
ar=arr[:,[1,3]]
print(ar)

[[0.20766077 0.44353579]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.43811321 0.49294138]]


# 8. 创建一个一维数组，提取所有大于10的元素。

In [50]:
arr=np.random.randint(-21,21,20)
print(arr)

[ -9  -2  -1  19  13 -15   2   5   8 -21   1  15  15 -11 -10   4 -19   0
  17   0]


In [54]:
print(arr[arr>10])  #1
print(np.extract(arr>10,arr))  #2

[19 13 15 15 17]
[19 13 15 15 17]


# 9. 将数组中所有负数替换为0。

In [61]:
arr3=np.where(arr<0,0,arr)  #1
print(arr3)
arr[arr<0]=0 #2
print(arr)

[ 0  0  0 19 13  0  2  5  8  0  1 15 15  0  0  4  0  0 17  0]
[ 0  0  0 19 13  0  2  5  8  0  1 15 15  0  0  4  0  0 17  0]


# 10. 获取数组中最大值和最小值的索引（使用`argmax`和`argmin`）。

In [58]:
print(np.argmin(arr))
print(np.argmax(arr))

0
3
