In [1]:
import numpy as np

# 1. 将一维数组(12,)重塑为3×4矩阵。

In [2]:
np.random.seed(520)
arr=np.random.randint(-12,12,12)
print(arr)
arr2=arr.reshape(3,4)
print(arr2)

[  0  -1   8   3   3   7   6   5  -4 -11   7   1]
[[  0  -1   8   3]
 [  3   7   6   5]
 [ -4 -11   7   1]]


# 2. 将3×4矩阵展平为一维数组。

In [3]:
arr2=np.random.rand(3,4)
print(arr2)
print(arr2.reshape(-1))  #1
print(arr2.flatten())    #2
print(arr2.ravel())      #3

[[0.62779295 0.59496407 0.85741886 0.49583801]
 [0.76153861 0.50087912 0.52028217 0.03030738]
 [0.17918249 0.42265821 0.9789235  0.80976508]]
[0.62779295 0.59496407 0.85741886 0.49583801 0.76153861 0.50087912
 0.52028217 0.03030738 0.17918249 0.42265821 0.9789235  0.80976508]
[0.62779295 0.59496407 0.85741886 0.49583801 0.76153861 0.50087912
 0.52028217 0.03030738 0.17918249 0.42265821 0.9789235  0.80976508]
[0.62779295 0.59496407 0.85741886 0.49583801 0.76153861 0.50087912
 0.52028217 0.03030738 0.17918249 0.42265821 0.9789235  0.80976508]


# 3. 创建两个2×3矩阵，垂直堆叠成4×3。

In [4]:
A=np.random.randint(1,100,(2,3))
B=np.random.randint(1,100,(2,3))
print(A)
print(B)
print(np.vstack((A,B)))  #1
print(np.concatenate((A,B),axis=0))  #2

[[28 30 95]
 [14  9 71]]
[[29 55 25]
 [ 4 10 25]]
[[28 30 95]
 [14  9 71]
 [29 55 25]
 [ 4 10 25]]
[[28 30 95]
 [14  9 71]
 [29 55 25]
 [ 4 10 25]]


# 4. 创建两个3×2矩阵，水平堆叠成3×4

In [6]:
arr1=np.random.randint(0,100,(3,2))
arr2=np.random.randint(0,100,(3,2))
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2))) #1
arr=np.hstack((arr1,arr2))
print(np.concatenate((arr1,arr2),axis=1)) #2

[[22 29]
 [36 83]
 [52 63]]
[[64 11]
 [31 77]
 [31 82]]
[[22 29 64 11]
 [36 83 31 77]
 [52 63 31 82]]
[[22 29 64 11]
 [36 83 31 77]
 [52 63 31 82]]


# 5. 将3×4矩阵按行分割成3个1×4的数组。

In [21]:
arr=np.arange(12).reshape(3,4)
print(arr)
log=np.split(arr,3,axis=0)
print(log)
for i in log:  #1
    print(i)
l=np.vsplit(arr,3)
for i in l:  #2
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


# 6. 将3×4矩阵按列分割成2个3×2的数组。

In [28]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(np.split(arr,2,axis=1))  #1  
print(np.hsplit(arr,2))# 2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# 7. 使用`newaxis`将一维数组(5,)变成列向量(5,1)。

In [40]:
a=np.random.randint(0,100,5)
print(a)
print(a[:,np.newaxis])
print(a[np.newaxis,:])

[21 59 57 33  9]
[[21]
 [59]
 [57]
 [33]
 [ 9]]
[[21 59 57 33  9]]


# 8. 使用`concatenate`沿指定轴合并两个三维数组。

In [46]:
arr1=np.random.randn(2,3,4)
arr2=np.random.randn(2,3,4)
print(np.concatenate((arr1,arr2),axis=0))

[[[ 1.08672606 -0.16670709 -1.15405353  0.60269661]
  [ 0.01302277  1.35729043  0.91839045 -1.79018121]
  [-1.17953076 -0.23922085  1.48202471  1.60271514]]

 [[ 0.44452156  0.42966352  0.38406465 -0.75920801]
  [-0.6710433   0.46866233 -0.4637061  -0.75178285]
  [ 0.67194936 -0.01613007 -1.38032459 -1.31365798]]

 [[-0.07673588 -1.49099993  2.76125994  0.50164063]
  [ 1.8222082  -1.11465466 -2.88090987 -1.34946803]
  [ 0.04224957  0.52063    -0.11916615 -0.33892019]]

 [[ 1.68685532  0.00551713 -1.88394628  1.70333791]
  [-0.82323107 -0.33898378  0.06204675  0.68548354]
  [ 0.10733197 -1.6520769  -0.84850485 -1.91480804]]]


# 9. 给数组增加一个维度（例如从(3,4)变成(1,3,4)）

In [68]:
np.random.seed(520)
arr=np.random.randint(0,100,(3,4))
print(arr)
a=arr[np.newaxis,:,:]
print(a)
print(a.shape)

[[44 27 84 15]
 [83 82 81 40]
 [25  1 51 92]]
[[[44 27 84 15]
  [83 82 81 40]
  [25  1 51 92]]]
(1, 3, 4)


# 10. 删除数组中大小为1的维度（`squeeze`）。

In [63]:
print(a.shape)
b=np.squeeze(a)
print(b)
print(b.shape)

(1, 3, 4)
[[44 27 84 15]
 [83 82 81 40]
 [25  1 51 92]]
(3, 4)
