In [2]:
import numpy as np 

# 1. 对数组每个元素求平方根。

In [6]:
arr=np.array([1,36,49,81])
print(np.sqrt(arr))

[1. 6. 7. 9.]


# 2. 对数组每个元素求自然对数。

In [8]:
print(np.log(arr))

[0.         3.58351894 3.8918203  4.39444915]


# 3. 计算两个数组的对应元素之和、差、积、商。

In [12]:
a=np.arange(1,11)
b=np.arange(1,11)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# 4. 计算数组的三角函数（sin, cos）并比较。

In [14]:
arr=np.linspace(0,np.pi/2,5)
print(arr)
print(np.sin(arr))
print(np.cos(arr))

[0.         0.39269908 0.78539816 1.17809725 1.57079633]
[0.         0.38268343 0.70710678 0.92387953 1.        ]
[1.00000000e+00 9.23879533e-01 7.07106781e-01 3.82683432e-01
 6.12323400e-17]


# 5. 使用`exp`计算e的幂。

In [18]:
print(np.exp(5))

148.4131591025766


# 6. 对数组四舍五入到小数点后2位

In [25]:
np.random.seed(520)
arr=np.random.uniform(0,12,12)
print(arr)
print(np.round(arr,2))

[ 5.30302813  2.49192924  0.17494935  5.32242953  7.863873    3.74763723
  0.71535134  4.48622933  2.45812007  2.49964793 11.82368745  9.11329023]
[ 5.3   2.49  0.17  5.32  7.86  3.75  0.72  4.49  2.46  2.5  11.82  9.11]


# 7. 使用`modf`将数组拆分成整数和小数部分

In [26]:
print(np.modf(arr))

(array([0.30302813, 0.49192924, 0.17494935, 0.32242953, 0.863873  ,
       0.74763723, 0.71535134, 0.48622933, 0.45812007, 0.49964793,
       0.82368745, 0.11329023]), array([ 5.,  2.,  0.,  5.,  7.,  3.,  0.,  4.,  2.,  2., 11.,  9.]))


# 8. 实现数组的逐元素比较（大于、小于、等于），返回布尔数组。

In [39]:
np.random.seed(520)
a=np.random.randint(-150,150,10)
b=np.random.randint(-150,150,10)
print(a)
print(b)
print(">",a>b)
print("<",a<b)
print("=",a==b)

[  22  -43   62   89 -135  146    3 -149  105   68]
[ 114  142  -23  -57 -137   82 -123 -121   94 -137]
> [False False  True  True  True  True  True False  True  True]
< [ True  True False False False False False  True False False]
= [False False False False False False False False False False]


# 9. 使用`where`实现条件赋值：将数组中大于0.5的元素替换为1，否则为0。

In [40]:
print(np.where(a>0.5,1,0))

[1 0 1 1 0 1 1 0 1 1]


# 10. 计算数组的绝对值、符号函数（`sign`）。

In [43]:
print(np.abs(a))
print(np.sign(a))

[ 22  43  62  89 135 146   3 149 105  68]
[ 1 -1  1  1 -1  1  1 -1  1  1]
