In [2]:
import numpy  as np

# 1. 计算两个2×2矩阵的乘积（`dot`或`@`）

In [8]:
np.random.seed(520)
arr=np.random.randint(0,100,(2,2))
arr2=np.random.randint(0,100,(2,2))
print(arr)
print(arr2)
print(arr@arr2)
print(np.dot(arr,arr2))

[[44 27]
 [84 15]]
[[83 82]
 [81 40]]
[[5839 4688]
 [8187 7488]]
[[5839 4688]
 [8187 7488]]


# 2. 计算3×3矩阵的行列式。

In [15]:
arr=np.random.randint(0,10,(3,3))
print(arr)
print(np.linalg.det(arr))

[[6 8 3]
 [9 9 8]
 [8 5 3]]
137.00000000000003


# 3. 求3×3矩阵的逆矩阵。

In [16]:
print(np.linalg.inv(arr))

[[-0.09489051 -0.06569343  0.27007299]
 [ 0.27007299 -0.04379562 -0.15328467]
 [-0.19708029  0.24817518 -0.13138686]]


# 4. 解线性方程组：  
   \[
   \begin{cases}
   2x + y = 5 \\
   x - 3y = 6
   \end{cases}
   \]  
   用矩阵形式`Ax = b`求解。

In [19]:
A=np.array([[2,1],[1,-3]])
b=np.array([5,6])
x=b@np.linalg.inv(A)
print(x)

[ 3. -1.]


# 5. 计算矩阵的特征值和特征向量。

In [9]:
arr=np.arange(16).reshape(4,4)
print(arr)
a,b=np.linalg.eig(arr)
print(a,b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 3.24642492e+01 -2.46424920e+00 -1.38326006e-15  1.11958422e-15] [[-0.11417645  0.7327781   0.53831742 -0.17497626]
 [-0.3300046   0.28974835 -0.64242635 -0.1535541 ]
 [-0.54583275 -0.15328139 -0.33009957  0.83203698]
 [-0.76166089 -0.59631113  0.4342085  -0.50350662]]


# 6. 计算两个向量的内积和外积。

In [4]:
np.random.seed(520)
a=np.random.randint(0,5,(3,4))
b=np.random.randint(0,5,(3,4))  
print(a)
print(b)            # 内积：逐元素相乘后的和，结果为一个标量
print(np.sum(a*b))  # 对应多维
a=np.array([1,2,3]) # 对应一维
b=np.array([4,5,6])
print(np.dot(a, b))
print(a @ b)
print(np.inner(a, b))    
print("\n", "外积")  #
print(np.outer(a,b))

[[4 3 3 4]
 [3 2 1 0]
 [1 1 3 4]]
[[2 0 0 4]
 [3 0 0 3]
 [4 2 2 4]]
61
32
32
32

 外积
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# 7. 对矩阵进行奇异值分解（SVD）

In [2]:
a=np.array([[1,2],[3,4],[5,6]])
u,s,vt=np.linalg.svd(a)
print(a)
print(u)
print(s)
print(vt)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# 8. 计算矩阵的迹（对角线元素之和）。

In [5]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(np.trace(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
15


# 9. 求矩阵的范数（Frobenius范数）。

In [7]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(np.linalg.norm(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
22.494443758403985


# 10. 使用`lstsq`求解超定线性方程组（最小二乘）。

In [ ]:
A=np.array