In [1]:
import numpy as np

# 1. 将一维数组保存为二进制`.npy`文件，再读取回来

In [3]:
arr=np.array([1,2,3])
np.save("array.npy",arr)
loaded=np.load("array.npy")
print(loaded)

[1 2 3]


# 2. 将多个数组保存为压缩的`.npz`文件，并读取。

In [13]:
np.random.seed(520)
arr1=np.random.randint(0,100,(10,21))
arr2=np.random.randint(0,100,(10,21))
arr3=np.random.randint(0,100,(10,21))
arr4=np.random.randint(0,100,(10,21))
arr5=np.random.randint(0,100,(10,21))
np.savez("arrays.npz",arr1,arr2,arr3,arr4,arr5)
loads=np.load("arrays.npz")
print(loads["arr_0"])

[[44 27 84 15 83 82 81 40 25  1 51 92 45 90  8 55 36 35 32 48 91]
 [93 98 50 13 60 16 65 27 29 94 13  8 99 70 28 54 24  3  9 24 72]
 [99 15 15  4 81 91 75 21 42 97 39 22 29 36 83 52 63 64 11 31 77]
 [31 82 40 20 29 11  4 81 41 24  2  7  3 82 12  5 78  6  7 58 66]
 [39 76 83 20 40 34 70 23 47 90 93 51  0 86 36 36 74 11 89 66 21]
 [38 21 72 31 15 73 40 40 54 86 51 73 70  0 90 21 59 57 33  9  4]
 [41 32 82 53 61 16 46 14 68 92 83 34 81 71 66 47 83  7 96  9 82]
 [66 70 89 34 77 78 58 26 79 84 25 24 93 47 19 17 25  9 76 21 28]
 [43  8 81 26  7 81 58 56 35 95 23 19 12 49 11 90  1 42 96 17 55]
 [14 78 65 73 97 14 41  5 96 66 53 24 85 43 61 68 28 48 32 41 54]]


# 3. 将二维数组保存为文本文件（如CSV），再用`loadtxt`读取。

In [21]:
np.random.randint(520)
arr=np.random.randint(0,10,(5,2))
print(arr)
np.savetxt("arr.csv",arr,delimiter=",")
loads=np.loadtxt("arr.csv",delimiter=",")
print(loads)

[[2 0]
 [7 4]
 [0 1]
 [3 5]
 [5 7]]
[[2. 0.]
 [7. 4.]
 [0. 1.]
 [3. 5.]
 [5. 7.]]


# 4. 使用`genfromtxt`读取带缺失值的文本文件。 

In [30]:
with open("txt.csv","w") as f:
    f.write("1,2,3\nN,4,5\n7,8,9")
data=np.genfromtxt("txt.csv",delimiter=",",missing_values="N",filling_values=0)
print(data)
              

[[1. 2. 3.]
 [0. 4. 5.]
 [7. 8. 9.]]


# 5. 将数组保存为TXT格式，并指定分隔符为逗号。

In [31]:
arr=np.array([1,2,3])
np.savetxt("a.txt",arr,delimiter=",")
lopads=np.loadtxt("a.txt",delimiter=",")
print(lopads)

[1. 2. 3.]
