In [2]:
import numpy as np

# 1. 使用布尔数组提取数组中所有大于0的元素。

In [13]:
np.random.seed(520)
arr=np.random.randint(0,3,12)
print(arr)
a=arr>0
print(a)
print(arr[a])

[0 0 2 1 0 1 1 0 1 2 0 2]
[False False  True  True False  True  True False  True  True False  True]
[2 1 1 1 1 2 2]


# 2. 将数组中所有非数字（NaN）替换为0。

In [11]:
arr=np.array([np.nan,12,545,745,np.nan,55,np.nan])
print(np.isnan(arr))
arr[np.isnan(arr)]=0
print(arr)

[ True False False False  True False  True]
[  0.  12. 545. 745.   0.  55.   0.]


# 3. 统计数组中大于某个阈值的元素个数。

In [20]:
np.random.seed(520)
arr=np.random.randint(0,50,20)
print(arr)
count=np.sum(arr>=25)
print(count)
print(np.sum(np.where(arr>=25,1,0)))

[44 43 27 20 47 15 19 18 17 40 25  1 28 45 39 26  8 46 48 36]
13
13


# 4. 使用布尔索引修改满足条件的元素（如将所有奇数变为-1）。

In [22]:
np.random.seed(520)
arr=np.random.randint(0,50,20)
print(arr)
print(np.where(arr%2!=0,-1,arr))

[44 43 27 20 47 15 19 18 17 40 25  1 28 45 39 26  8 46 48 36]
[44 -1 -1 20 -1 -1 -1 18 -1 40 -1 -1 28 -1 -1 26  8 46 48 36]


# 5. 找出数组中同时满足两个条件的元素（例如大于5且小于10）。

In [27]:
np.random.seed(520)
arr=np.random.randint(0,20,20)
print(arr)
a=(arr>=5)&(arr<=10)
print(arr[a])

[12 11 15 15 19 18 17  8  1 19 13  7  8 14 16  4  3  0 16  4]
[8 7 8]


# 6. 用花式索引提取指定位置的元素（索引数组）。

In [31]:
np.random.seed(520)
arr=np.random.randint(0,20,20)
print(arr)
print(arr[[2,5,6]])

[12 11 15 15 19 18 17  8  1 19 13  7  8 14 16  4  3  0 16  4]
[15 18 17]


# 7. 创建一个3×3矩阵，用两个一维索引数组（行索引和列索引）提取对应元素。

In [35]:
np.random.seed(520)
arr=np.random.randint(0,20,(3,3))
print(arr)
a1=[0,1,2]
a2=[0,1,2]
print(arr[a1,a2])

[[12 11 15]
 [15 19 18]
 [17  8  1]]
[12 19  1]


# 8. 使用`take`和`put`函数进行索引和赋值。

In [37]:
a = np.array([10,20,30,40])
indices = [0,2]
taken = a.take(indices)
print(taken)
a.put([1,3], [99,88])
print(a)

[10 30]
[10 99 30 88]


# 9. 使用`ix_`函数构造索引器，提取不连续的行和列。

In [47]:
np.random.seed(520)
arr=np.random.randint(0,3,(5,5))
print(arr)
rows=[1,2,3]
cols=[0,4]
print(np.ix_(rows,cols))
print(arr[1,0],arr[1,4],arr[2,0],arr[2,4],arr[3,0],arr[3,4])
print(arr[np.ix_(rows,cols)])

[[0 0 2 1 0]
 [1 1 0 1 2]
 [0 2 0 0 0]
 [0 2 0 1 2]
 [2 1 0 0 0]]
(array([[1],
       [2],
       [3]]), array([[0, 4]]))
1 2 0 0 0 2
[[1 2]
 [0 0]
 [0 2]]


# 10. 对一维数组，找出局部最大值的索引（即比前后元素都大的位置）

In [59]:
np.random.seed(520)
arr=np.random.randint(0,100,10)
print(arr)
js=[]
ji=[]
for i in range(1,len(arr)-1):
    if arr[i]>arr[i-1] and arr[i]>arr[i+1]:
        ji.append(i)
        js.append(arr[i])
print(js)
a=(arr[1:-1]>arr[:-2])&(arr[1:-1]>arr[2:])
print(a)
p = np.arange(1, len(arr)-1)[a]
print(ji) 
print(p)

[44 27 84 15 83 82 81 40 25  1]
[np.int32(84), np.int32(83)]
[False  True False  True False False False False]
[2, 4]
[2 4]
