
## 1.ndarray 特性   (N-dimensional arry N维数组）

In [5]:
import numpy as np

In [24]:
arr=np.array(5)
ar=np.array([5,6,7])
print(arr)
print("维度:",arr.ndim) #number of dimensions
print(ar)
print("维度",ar.ndim)
list1=[5,6,7]
ar=np.array(list1, dtype=np.float64)   #强制转化
print(ar)

5
维度: 0
[5 6 7]
维度 1
[5. 6. 7.]


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("维度",arr.ndim)

[[1 2 3]
 [4 5 6]]
维度 2


In [14]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("维度",arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
维度 2


### 同质性

In [18]:
arr=np.array([1,"jkhjkhkjh"])
print(arr)
print("元素一：",arr[0])
print("元素二：",arr[1])
print("维度",arr.ndim)

['1' 'jkhjkhkjh']
元素一： 1
元素二： jkhjkhkjh
维度 1


In [29]:
arr1=np.array([12323,"1225"])
print(arr1)

['12323' '1225']


## 2.ndarrary 属性

In [20]:
arr=np.array(1)
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("数组的类型：",arr.dtype)
print("数组元素个数：",arr.size)
print("数组转置：",arr.T)

数组的形状： ()
数组的维度： 0
数组的类型： int64
数组元素个数： 1
数组转置： 1


In [21]:
arr=np.array([1,2,3])
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("数组的类型：",arr.dtype)
print("数组元素个数：",arr.size)
print("数组转置：",arr.T)

数组的形状： (3,)
数组的维度： 1
数组的类型： int64
数组元素个数： 3
数组转置： [1 2 3]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("数组的类型：",arr.dtype)
print("数组元素个数：",arr.size)
print("数组转置：",arr.T)

数组的形状： (2, 3)
数组的维度： 2
数组的类型： int64
数组元素个数： 6
数组转置： [[1 4]
 [2 5]
 [3 6]]


## 3.ndarry的创建

### （1）普通如np.array

###  (2) copy之前的

In [37]:
arr00=np.copy(arr1)
print(arr00)

[[1. 1. 1.]
 [1. 1. 1.]]


### （3）已有的结构

In [40]:
arr00=np.full((5,6),8)
arr=np.zeros((2,3))
arr01=np.zeros_like(arr00)
print(arr,"\n")
print(arr01)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [42]:
arr1=np.ones((2,3))
arr10=np.ones_like(arr00)
print(arr1,"\n")
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [43]:
arr2=np.empty((6,3))
arr20=np.empty_like(arr00)
print(arr2,"\n")
print(arr20)

[[1.13016249e-311 5.08887615e-322 0.00000000e+000]
 [0.00000000e+000 6.23053953e-307 1.94920325e-153]
 [2.59549728e+251 6.04318383e+241 5.49715098e-143]
 [5.56111702e+180 1.16391405e-028 2.59032995e-144]
 [9.96916465e-143 1.05894728e-153 6.01123204e+175]
 [2.58643861e+185 4.82406562e+228 2.59304413e-306]] 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [44]:
arr3=np.full((5,3),6)
arr30=np.full_like(arr00,100)
print(arr3,"\n")
print(arr30)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]] 

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
