# 1.温度 
求  平均 max min   超过30度的天数

In [1]:
import numpy as np
np.random.seed(10)
arr=np.random.randint(19,36,24)
print(arr)

[28 23 34 19 35 27 28 19 29 27 23 35 23 34 30 30 20 27 23 33 32 24 32 32]


In [11]:
print("平均气温")
print("%.3f" %np.mean(arr))
print("最高气温")
print("%d" %np.max(arr))
print("最低气温")
print("%d" %np.min(arr))
print("超过30度的天数")
print(len(arr[arr>30]))
print(np.sum(np.where(arr>30,1,0)))
print(np.cumsum(np.where(arr>30,1,0))[-1])
print(np.count_nonzero(arr>30))

平均气温
27.792
最高气温
35
最低气温
19
超过30度的天数
8
8
8
8


# 2.成绩
计算平均分  中位数   标准差 
将成绩转化为百分制

In [29]:
np.random.seed(25)
score=np.random.randint(80,100,10)
print(score)
print(np.sort(score))

[84 95 92 98 88 84 85 81 87 83]
[81 83 84 84 85 87 88 92 95 98]


In [30]:
print("平均数: %.2f" %np.mean(score))
print("中位数：%d" %np.median(score))
print("标准差：%.2f" %np.std(score))

平均数: 87.70
中位数：86
标准差：5.29


# 3.矩阵运算  A+B   A*B   AB

In [31]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [35]:
print(A+B)
print(A*B)
print(A@B)
print(np.dot(A,B))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# 4.随机数的计算 
行 列  替换

In [44]:
np.random.seed(25)
arr=np.random.randint(0,10,(3,4))
print(arr)

[[4 6 7 2]
 [8 4 9 4]
 [5 1 7 3]]


In [48]:
print(np.max(arr,axis=0))  #列
print(np.max(arr,axis=1))  #行
print(np.min(arr,axis=1))
print(np.min(arr,axis=0))

[8 6 9 4]
[7 9 7]
[2 4 1]
[4 1 7 2]


In [53]:
print(np.where(arr%2!=0,-1,arr))
arr[arr%2!=0]=-1
print(arr)

[[ 4  6 -1  2]
 [ 8  4 -1  4]
 [-1 -1 -1 -1]]
[[ 4  6 -1  2]
 [ 8  4 -1  4]
 [-1 -1 -1 -1]]


# 5.数组变形

In [55]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [66]:
arr=np.reshape(arr,(3,4))
print(arr)
print("列数最大值",np.sum(arr,axis=0))
print("行数最小值",np.sum(arr,axis=1))
print("列平均值",np.mean(arr,axis=0))
print("行平均值",np.mean(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
列数最大值 [15 18 21 24]
行数最小值 [10 26 42]
列平均值 [5. 6. 7. 8.]
行平均值 [ 2.5  6.5 10.5]


# 6.布尔索引

In [9]:
np.random.seed(100)
arr=np.random.randint(0,20,(5,5))
print(arr)

[[ 8  3  7 15 16]
 [10  2  2  2 14]
 [ 2 17 16 15  4]
 [11 16  9  2 12]
 [ 4  1 13 19  4]]


In [10]:
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[15 16 14 17 16 15 11 16 12 13 19]
[[ 8  3  7  0  0]
 [10  2  2  2  0]
 [ 2  0  0  0  4]
 [ 0  0  9  2  0]
 [ 4  1  0  0  4]]


# 7.统计应用
总和 均值 方差
最大索引  最小索引

In [14]:
np.random.seed(25)
arr=np.random.randint(100,200,9)
print(arr)

[104 162 190 115 161 123 144 150 108]


In [17]:
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))
print(np.argmax(arr)+1)
print(np.argmin(arr)+1)

1257
139.66666666666666
752.6666666666666
27.434771124736336
3
1


# 8.数组拼接
水平拼接  垂直拼接

In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [30]:
arr=np.concatenate([arr1,arr2])
print(arr)
print(np.reshape(arr,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# 9.唯一值和排序
确定唯一值排序
确定出现次数

In [31]:
np.random.seed(25)
arr=np.random.randint(1,5,8)
print(arr)

[1 3 3 4 2 3 4 4]


In [44]:
arr1,arr2=np.unique(arr,return_counts=True)
print(arr1)
print(arr2)
d=[]

[1 2 3 4]
[1 1 3 3]


In [46]:
for i in range(len(arr1)):
    d=d+[len(arr[arr==arr1[i]])]
print(d)

[1, 1, 3, 3, 1, 1, 3, 3]


# 10.总和
## 销售 成本 
### 利润 平均值 标准差 利润最高天数

In [47]:
销售=np.random.randint(20,28,8)
成本=np.random.randint(15,21,8)
print(销售)
print(成本)

[24 22 25 20 24 24 21 25]
[19 20 16 18 15 18 19 20]


In [49]:
利润=销售-成本
print(利润)
print("平均值：",np.mean(利润))
print("标准差:",np.std(利润))
print("利润最高天数:",np.argmax(利润))

[5 2 9 2 9 6 2 5]
平均值： 5.0
标准差: 2.7386127875258306
利润最高天数: 2
