# （1）普通如np.array

In [6]:
import numpy as np

# (2) copy之前的

In [7]:
arr1=np.array([[3,2,1],[4,5,6]])
arr00=np.copy(arr1)
print(arr00)

[[3 2 1]
 [4 5 6]]


# （3）已有的结构

## 全零形

In [8]:
arr00=np.full((5,6),8)
arr=np.zeros((2,3))
arr01=np.zeros_like(arr00)
print(arr,"\n")
print(arr01)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


## 全一形

In [9]:
arr1=np.ones((2,3))
arr10=np.ones_like(arr00)
print(arr1,"\n")
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


## 随机

In [10]:
arr2=np.empty((6,3))
arr20=np.empty_like(arr00)
print(arr2,"\n")
print(arr20)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[27303467881726020 31244147623002222 25896114475761774 25896118771056716
  28429470870863987 27866439313522733]
 [28429415035764843 28429402150535283 31525639780892770 33214455279779961
  31244151918821477 25896127360729202]
 [28429402152435824 31525592535138422 33214481050108025 30399778527314020
  30962698416488565 33777431003005043]
 [32370094774747252 32370094775402601 31525717090238556 31525592536121445
  33214481050108025 30399778527314020]
 [30962698416488565 29836777034285171 31244164803723361 32088624093069407
  32651591225901165 34058953221341298]]


### 自定义

In [11]:
arr3=np.full((5,3),6)
arr30=np.full_like(arr00,100)
print(arr3,"\n")
print(arr30)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]] 

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
