### 等差数列   （start end step）   包前不包后

In [2]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)
arr=np.arange(2,20,1)
print(arr)

[1 3 5 7 9]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 等间隔数列 （start  end size ) 包前包后

In [4]:
arr =np.linspace(1,20,5)
print(arr)
arr =np.linspace(0,4,3,dtype=int)
print(arr)
arr=np.arange(0,101,20)
print(arr)
arr=np.linspace(0,100,6,dtype=int)
print(arr)

[ 1.    5.75 10.5  15.25 20.  ]
[0 2 4]
[  0  20  40  60  80 100]
[  0  20  40  60  80 100]


### 对数间隔数列

In [5]:
arr=np.logspace(2,20,22,base=6,dtype=int)
print(arr)

[              36              167              776             3607
            16759            77846           361595          1679616
          7801835         36239614        168333425        781910683
       3631984055      16870607413      78364164096     364002437125
    1690795477264    7853764300355   36480824863191  169453848091483
  787115059505805 3656158440062976]


In [6]:
arr=np.logspace(0,10,10,dtype=int)
print(arr)

[          1          12         166        2154       27825      359381
     4641588    59948425   774263682 10000000000]
