## 单位矩阵

In [1]:
import numpy as np

In [5]:
arr=np.eye(6,dtype=int)
print(arr)
print("\n")
arr=np.eye(4,5,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


## 对角矩阵

In [6]:
arr=np.diag([5,3,4,6])
print(arr)

[[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 6]]


## 随机矩阵

### 0~1 均匀 浮点 分布

In [7]:
arr=np.random.rand(2,3)
print(arr)

[[0.5311086  0.81370727 0.70334297]
 [0.80851268 0.81689536 0.38020933]]


### 指定范围区间  均匀 浮点 分布

In [11]:
arr=np.random.uniform(3,6,(5,5))
print(arr)

[[3.93246287 3.48739853 4.82407681 4.32350731 4.19432384]
 [5.75047263 4.59662033 5.02089976 4.101352   3.50939506]
 [4.24016411 4.84919081 4.63742143 5.01031464 5.84401285]
 [5.91869377 4.93207185 3.41024769 5.21355935 5.37172053]
 [3.7159826  5.57917396 4.54598007 5.74213169 5.43080263]]


In [9]:
arr=np.random.randint(3,6,(5,5))
print(arr)

[[3 3 5 5 3]
 [3 3 4 3 4]
 [3 5 3 3 5]
 [4 4 4 5 5]
 [5 5 3 5 5]]


### 随机范围区间（-3，3） 正态分布

In [14]:
arr=np.random.randn(6,4)
print(arr)

[[ 1.14218097 -1.09556434 -0.01518974  0.89243364]
 [ 0.09747898 -1.25143093 -0.90106751  0.7522721 ]
 [-0.1610472  -0.56715034  0.25463282  0.23670821]
 [ 0.13642424  1.92032616 -0.28875212 -0.15163222]
 [ 1.1811385  -1.41526191  1.01814418 -1.03047215]
 [-0.18238057  0.45523946 -1.35737867 -0.68048635]]


### 随机种子 确立种子后 固定随机数

In [20]:
np.random.seed(20)   
arr=np.random.randint(1,10,(5,5))
print(arr)
print("\n")
arr=np.random.randint(5,79,(6,6))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]
 [1 7 7 1 6]
 [8 6 3 7 4]
 [4 1 7 3 4]]


[[22 48 21 23 64 76]
 [34 50 11 68 29 23]
 [38 47  8 23 75 57]
 [27 19  9 32 13 11]
 [31 15 38 22 45 47]
 [65 35 41 13 53 24]]
