In [1]:
import numpy as np

# 一维数组

In [3]:
arr =np.random.randint(1,100,20)
print(arr)

[57 96 64 63 23 31 90  6 87  5 97 89 25 77 75 20 42 21 42 74]


In [10]:
print(arr[:])
print(arr[2:6])  #左闭右开
print(arr[slice(2,6)])
print(arr[(arr>90) & (arr<100)])
for i in range(20):
    print(arr[i])

[57 96 64 63 23 31 90  6 87  5 97 89 25 77 75 20 42 21 42 74]
[64 63 23 31]
[64 63 23 31]
[96 97]
57
96
64
63
23
31
90
6
87
5
97
89
25
77
75
20
42
21
42
74


## 二维数组

In [11]:
arr=np.random.randint(1,100,(5,6))
print(arr)

[[47 32 72 41 51 83]
 [82 49  1 99  1 91]
 [24 68 11  4 83 15]
 [90 69 75 45 41 61]
 [10 77 82 96 71 32]]


In [18]:
print(arr[1,2])
print(arr[1,:])#行数据
print(arr[2])
print(arr[:,2]) #列数据
print(arr[arr>50])

1
[82 49  1 99  1 91]
[24 68 11  4 83 15]
[72  1 11 75 82]
[72 51 83 82 99 91 68 83 90 69 75 61 77 82 96 71]
