# 加减乘除

In [1]:
import numpy as np

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*100)
print(a+100)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[100 200 300]
[101 102 103]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# 广播
# 同一维度或其中一个是一

In [9]:
a=np.array([1,2,3])  #1*3
b=np.array([[4],[5],[6]])  #3*1
print(a+b)
print(a-b)
print(a*b)
print(a@b)      #线性代数乘法运算

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[32]


# 矩阵的维度 和线代的维度不一样???????????