# 1.平方根

In [2]:
import numpy as np
print(np.sqrt(81),"\n")
print(np.sqrt([1,4,9]),"\n")
print(np.sqrt(np.array([[1,4,9],[4,9,9]])),"\n")

9.0 

[1. 2. 3.] 

[[1. 2. 3.]
 [2. 3. 3.]] 



# 2.指数  e^x

In [4]:
print(np.exp(3))
print(np.exp(1))

20.085536923187668
2.718281828459045


# 3.自然对数  ln x

In [7]:
print(np.log(2.71821))
print(np.log(1))

0.9999735754375005
0.0


# 4.三角函数

In [9]:
print(np.sin(1))
print(np.sin(np.pi/2))

0.8414709848078965
1.0


# 5.绝对值

In [15]:
arr=np.array([-1,-6,5,-2])
print(np.abs(arr))

[1 6 5 2]


# 6.a的b次幂

In [19]:
print(np.power(arr,8))

[      1 1679616  390625     256]


# 7.四舍五入

In [22]:
print(np.round(np.array([1.5,6.45544,4.445588882255565])))
arr=np.array([2.6,3.5,6.4,3.1])

[2. 6. 4.]


## 向上取

In [25]:
print(np.ceil(arr))
print(np.floor(arr))

[3. 4. 7. 4.]
[2. 3. 6. 3.]


# 8.检测缺失值

In [34]:
np.isnan([-1,25,np.nan,54])

array([False, False,  True, False])