In [2]:
import numpy as np

In [7]:
arr=np.random.randint(1,25,10)
print(arr)

[24  8  6 23  6  3 14  6  9 20]


In [8]:
print(np.sum(arr))  #求和

119


In [9]:
print(np.mean(arr))  #求平均值

11.9


In [11]:
print(np.median([1,2,4]))   #中位数
print(np.median([1,2,2,4,5,9]))

2.0
3.0


In [16]:
print(np.var([1,2,3,4]))  #方差
print(np.std([1,2,3,4]))  #标准差

1.25
1.118033988749895


In [25]:
np.random.seed(10)
arr=np.random.randint(1,100,20)
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79]
94 5
1 9


In [28]:
print(np.percentile(arr,20))   #分位数

15.200000000000001


In [13]:
arr=np.array([1,2,3,4])
print(np.sum(arr))
print(np.cumsum(arr))  #累计和
print(np.cumprod(arr)) #累积积

10
[ 1  3  6 10]
[ 1  2  6 24]
